### ISSUE TITLE
Redirects in the Werkzeug browser retain method, headers and params

### ISSUE THREAD

**Issue by jh-sportcaster** [elliterate/capybara.py#14]
[capybara.werkzeug.browser.Browser._process_and_follow_redirects](https://github.com/elliterate/capybara.py/blob/566b136e48e4f4cac87516a5fdacdded069a82be/capybara/werkzeug/browser.py#L54) handles redirects in what I would consider a wrong way. I'm talking specifically about <https://github.com/elliterate/capybara.py/blob/566b136e48e4f4cac87516a5fdacdded069a82be/capybara/werkzeug/browser.py#L61>

What it does at the moment is to retain basically all data from the original request, except the path, which it overrides. This means that if you for instance make a POST request to a URL, and that URL redirects to another page, the second request will be the same. This is a violation of HTTP/1.1 for the 303 status code (which demands a `GET` request for the new location), and – worse – inconsistent with how all browsers I know of handle 302 and possibly 301.

Thus, my proposal would be a diff of the following nature:

    -                self._process(method, path, params, headers)
    +                self._process('GET', path, None, headers)

Whatever `params` would be needed for the subsequent request would be indicated in the response's `Location` header.

I am unsure whether `headers` should be retained in its entirety, but I don't know what would be consistent with browser behaviour.

**Comment by elliterate** [comment]
Thanks for the bug report!

You're spot-on about the need to use `GET` and exclude the `params`. The `headers` should be fine—indeed, necessary—as they're only used internally to specify the `Referer`.
