### ISSUE TITLE
Django test cases cooperation

### ISSUE THREAD

**Issue by pkrefta** [elliterate/capybara.py#19]
Hi @elliterate ,

Thanks for your great work. I've configured capybara.py to support my Django app and it works OK. I'm able to visit webpages and basic functions works as expected 👍 

I've built my tests using `django.test.TestCase` and before visiting some URL i'm adding some items to my database to display them. But unfortunately in browser my application's database is empty.

My skeleton looks like this

```python
import capybara
import capybara.dsl
from capybara.selenium.driver import Driver
from my_project.wsgi import application

from django.test import TestCase

@capybara.register_driver("selenium_chrome")
def init_selenium_chrome_driver(app):
    return Driver(app, browser="chrome")

capybara.default_driver = "selenium_chrome"
capybara.app = application


class IntegrationTest(TestCase):
    def setUp(self):
        self.page = capybara.dsl.page

    def tearDown(self):
        capybara.reset_sessions()

    def test_show_index_page(self):
        # Add some data here
        self.prepare_test_data()        

        # Unfortunately here, in browser none of test data is available
        self.page.visit('/')
```

Is this an expected behaviour or am I doing something wrong ?

**Comment by elliterate** [comment]
I haven’t used Django to build a proper app, let alone write acceptance tests, but if I had to hazard a guess...

I’d bet that (1) the test and the server are using separate database connections and (2) the data you create is wrapped in a transaction that is rolled back at the end of the test. That would prevent the server from ever seeing the test data.

In Rails, one would either (a) share the database connection between the server and the test or (b) disable the use of transactions in the test, instead using truncation to reset the database between tests. I’m willing to bet there’s a way for you to do at least one of those with Django.

**Comment by elliterate** [comment]
From a quick read of the docs, it sounds like you might need to use [`TransactionTestCase`](https://docs.djangoproject.com/en/2.0/topics/testing/tools/#django.test.TransactionTestCase) as your base class. (Counter-intuitively, it uses truncation to reset between tests, whereas `TestCase` uses transactions.)

**Comment by elliterate** [comment]
I was able to write a simple, passing integration test against the Django tutorial app by using `TransactionTestCase`, so I think that's all you need.

But if for some reason you're still having trouble, I created [a mailing list](http://groups.google.com/group/capybara-py/) where I'm happy to keep helping.
