### ISSUE TITLE
Add more maintainers

### ISSUE THREAD

**Issue by dwt** [elliterate/capybara.py#24]
Hi there,

as someone who uses capybara (ruby) to test my python projects, this seems like a godsend. However, the project seems also quite a bit too much dead - as in not releasing anything.

Have you thought about adding more maintainers? Perhaps moving the project into it's own organisation? Because as far as I can tell, this project is hugely missing in the python acceptance testing ecosystem.

**Comment by dwt** [comment]
@elliterate ping?

**Comment by dwt** [comment]
@elliterate ping again?

**Comment by dwt** [comment]
@elliterate I've been able to get some input from @twalpole of team capybara. He would actually consider adding this capybara port to the teamcapybara namespace.

I think this could be great for several reasons, especially:
- It could give the project a lot of visibility
- It could open the door to make it much easier to gain more drive by contributions / maintainers

What do you think about that?

I really would like to help, at least in merging the open and mostly clean pull requests and create up to date releases.

I am a bit at a loss how to best demonstrate to you that I would be able to do so, or how to get the ball rolling to add other maintainers. I'd really like some input on that from you.

It kind of seems as if you are not doing so much python anymore these days - is that part of the reason why this project has gone a bit on the back burner for you? Any other reasons? Do you plan to come back to this project shortly / eventually?

This really is such a great piece of code, it would be a total shame for this project not to shine. Compared with the other wrappers around / on top of selenium, this is just _so much better_.

(I'm currently creating a detailed comparison on the different frameworks for browser testing on python, and am planning to turn that into a talk eventually: [preview / development here](https://github.com/dwt/browser-automation-comparison)).

**Comment by dwt** [comment]
@elliterate I'd really appreciate some input from you here. This is a terrific project, and it currently is very much lacking for your time.

Which I understand - but then you should really

a) At least advertise that you are searching for more maintainers
b) consider moving the project to the teamcapybara namespace to improve the visibility
c) consider adding more maintainers (yes I'm offering, and yes I know thats a big ask).

**Comment by elliterate** [comment]
You're more than welcome to open a pull request with bug fixes or suggested enhancements.
