### ISSUE TITLE
Support playwright-python

### ISSUE THREAD

**Issue by dwt** [elliterate/capybara.py#25]
[Playwright](https://pypi.org/project/playwright/) is a new kid on the block for browser-automation, with some interesting features. Since it also allows selection by xpath, there should not be a principle reason why it can't be supported as an alternative to Selenium in capybara.

Playwright has some interesting features, but it's API sucks - even though not quite as hard as selenium.

What do you think?

**Comment by elliterate** [comment]
I tried to structure this port such that, like the Ruby version, alternative drivers could be implemented as external packages. This package contains a test suite that can be imported and executed against a driver implemented in another package.

As a demonstration, I attempted to do just that with WebTest. (See: https://github.com/elliterate/capybara-webtest.)

**Comment by dwt** [comment]
Very interesting, I'll take a look at that!

**Comment by dwt** [comment]
That actually looks quite doable. I'm still running all my browser testing (for python projects) through ruby using capybara, but I definitely want to switch, and then this would be a great project to allow for the really nice debugging helper options from playwright.

Some of the API differences probably make for a harder match, e.g. the way they handle dialogs is completely different than selenium. I imagine that that will create some problems. But that's a problem for when I actually try that.

**Comment by elliterate** [comment]
Closing, as this is more appropriately implemented as an external package.
